---
- name: This scrpit is for managing user and group.
  hosts: all
  become: true
  tasks:

  - name: Creating group
    group:
       name: webadmin
       state: present

  - name: Creating user
    user:
        name: asim
        group: webadmin
        state: present
        create_home: yes
        comment: "Test user"
