---
# tasks file for setup-httpd-role
- name: Installing httpd package in redhat
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: starting httpd service

- name: Installing apache2 package in debian
  yum:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: starting apache2 service

- name: copying file
  copy:
    src: /home/ansadmin/yml_script/index.html
    dest: /var/www/html/
