---
# handlers file for setup-httpd-role
- name: starting httpd service
  service:
    name: httpd
    state: started


- name: starting apache2 service
  service:
    name: apache2
    state: started
